#!/usr/bin/env bash
#
# Concatenate the 7 authored CSS files into a single css/app.css so the page
# makes ONE render-blocking stylesheet request instead of seven (clears the
# mobile Lighthouse render-blocking penalty). This is NOT a bundler or minifier
# — just `cat` in the cascade order index.html relies on (responsive last so its
# overrides win). Edit the source files in css/, never css/app.css directly.
#
# CI runs this and fails if css/app.css is out of sync (see .github/workflows/ci.yml).
#
# Usage: ./scripts/build-css.sh
set -euo pipefail
cd "$(dirname "$0")/.."

ORDER=(
  css/fonts.css
  css/base.css
  css/components.css
  css/nav.css
  css/hero.css
  css/sections.css
  css/responsive.css
)

{
  printf '/* GENERATED by scripts/build-css.sh — do not edit. Edit the source files in css/. */\n'
  cat "${ORDER[@]}"
} > css/app.css

echo "Built css/app.css from ${#ORDER[@]} sources ($(wc -c < css/app.css) bytes)."

# Stamp sitemap <lastmod> at build time so the deployed copy is never stale.
# (Runs in CI too — CI's freshness diff only covers css/app.css, so this is safe.)
TODAY="$(date +%Y-%m-%d)"
tmp="$(mktemp)"
sed "s|<lastmod>[^<]*</lastmod>|<lastmod>${TODAY}</lastmod>|" sitemap.xml > "$tmp" && mv "$tmp" sitemap.xml
echo "Stamped sitemap.xml lastmod ${TODAY}."
